#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Kunstmaan\GitHubFlowChangelog\Command\ChangelogCommand;
use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');
$command = new ChangelogCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
